import pypowsybl


LF_PROVIDER = {
    'slackBusSelectionMode': 'LARGEST_GENERATOR',
    # 'slackBusesIds': '',
    # 'lowImpedanceBranchMode': 'REPLACE_BY_ZERO_IMPEDANCE_LINE',
    'voltageRemoteControl': 'True',
    # 'slackDistributionFailureBehavior': 'LEAVE_ON_SLACK_BUS',
    'loadPowerFactorConstant': 'False',
    # 'plausibleActivePowerLimit': '5000.0',
    'slackBusPMaxMismatch': '0.1',
    # 'voltagePerReactivePowerControl': 'False',
    # 'generatorReactivePowerRemoteControl': 'False',
    # 'transformerReactivePowerControl': 'False',
    'maxNewtonRaphsonIterations': '15',
    'maxOuterLoopIterations': '30',
    # 'newtonRaphsonConvEpsPerEq': '1.0E-4',
    'voltageInitModeOverride': 'FULL_VOLTAGE',
    'transformerVoltageControlMode': 'INCREMENTAL_VOLTAGE_CONTROL',
    'shuntVoltageControlMode': 'INCREMENTAL_VOLTAGE_CONTROL',
    # 'minPlausibleTargetVoltage': '0.8',
    # 'maxPlausibleTargetVoltage': '1.2',
    # 'minRealisticVoltage': '0.5',
    # 'maxRealisticVoltage': '2.0',
    # 'reactiveRangeCheckMode': 'MAX',
    'lowImpedanceThreshold': '3.0E-5',
    # 'networkCacheEnabled': 'False',
    # 'svcVoltageMonitoring': 'True',
    # 'stateVectorScalingMode': None,
    # 'maxSlackBusCount': '1',
    # 'debugDir': '',
    # 'incrementalTransformerVoltageControlOuterLoopMaxTapShift': '3',
    # 'secondaryVoltageControl': 'False',
    # 'reactiveLimitsMaxPqPvSwitch': '3',
    'newtonRaphsonStoppingCriteriaType': 'PER_EQUATION_TYPE_CRITERIA',
    'maxActivePowerMismatch': '0.1',
    'maxReactivePowerMismatch': '0.1',
    'maxVoltageMismatch': '1.0E-4',
    'maxAngleMismatch': '1.0E-5',
    # 'maxRatioMismatch': '1.0E-5',
    # 'maxSusceptanceMismatch': '1.0E-4',
    # 'phaseShifterControlMode': 'CONTINUOUS_WITH_DISCRETISATION',
    # 'alwaysUpdateNetwork': 'False',
    # 'mostMeshedSlackBusSelectorMaxNominalVoltagePercentile': '95.0',
    # 'reportedFeatures': [],
    'slackBusCountryFilter': 'PL',
    # 'actionableSwitchesIds': [],
    # 'actionableTransformersIds': [],
    # 'asymmetrical': 'False',
    # 'minNominalVoltageTargetVoltageCheck': '20.0',
    # 'reactivePowerDispatchMode': 'Q_EQUAL_PROPORTION',
    # 'outerLoopNames': [],
    # 'useActiveLimits': 'True',
    # 'disableVoltageControlOfGeneratorsOutsideActivePowerLimits': 'False',
    # 'lineSearchStateVectorScalingMaxIteration': '10',
    # 'lineSearchStateVectorScalingStepFold': '1.33',
    # 'maxVoltageChangeStateVectorScalingMaxDv': '0.1',
    # 'maxVoltageChangeStateVectorScalingMaxDphi': '0.1745',
    # 'linePerUnitMode': 'IMPEDANCE',
    # 'useLoadModel': 'False',
    # 'dcApproximationType': 'IGNORE_R',
    # 'simulateAutomationSystems': 'False',
    # 'acSolverType': 'NEWTON_RAPHSON',
    # 'maxNewtonKrylovIterations': '100',
    # 'newtonKrylovLineSearch': 'False',
    'referenceBusSelectionMode': 'GENERATOR_REFERENCE_PRIORITY',  # FIRST_SLACK
    # 'writeReferenceTerminals': 'True',
    'voltageTargetPriorities': 'GENERATOR,TRANSFORMER,SHUNT',
}

SA_PROVIDER = {
    'contingencyPropagation': 'false',
    'threadCount': '2',
    # 'dcFastMode': 'true',
    'createResultExtension': 'true',
    # 'contingencyActivePowerLossDistribution': 'Default',
}

LF_PARAMETERS = pypowsybl.loadflow.Parameters(
    voltage_init_mode=pypowsybl.loadflow.VoltageInitMode.UNIFORM_VALUES,
    transformer_voltage_control_on=True,
    use_reactive_limits=True,
    phase_shifter_regulation_on=False,
    twt_split_shunt_admittance=False,
    shunt_compensator_voltage_control_on=True,
    read_slack_bus=False,
    write_slack_bus=True,
    distributed_slack=True,
    balance_type=pypowsybl.loadflow.BalanceType.PROPORTIONAL_TO_GENERATION_P_MAX,
    dc_use_transformer_ratio=True,
    countries_to_balance=None,
    connected_component_mode=pypowsybl.loadflow.ConnectedComponentMode.ALL,
    dc_power_factor=1.0,
    provider_parameters=LF_PROVIDER,
)

SA_PARAMETERS = pypowsybl.security.Parameters(
    load_flow_parameters=LF_PARAMETERS,
    increased_violations_parameters=None,
    provider_parameters=SA_PROVIDER,
)
